package rules

import eu.patternengine.model.*

//rule "Offer for Diamond"
//	when
//		productObject: Product(type=="diamond")
//	then
//		productObject.setDiscount(15);
//	end
//rule "Offer for Gold"
//	when
//		productObject: Product(type=="gold")
//	then
//		productObject.setDiscount(25);
//	end

rule "vulnerability Measurement Rule"
when
    $VMP: VulnerabilityMeasurementPolicy($cmp:=component, $staticscan:=staticScanPath, $dynamicscan:=dynamicScanURL, $fr:=scanningFrequency)
then
    System.out.println($VMP.toString());
end

